apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ttm-as-a-service
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: https://quay.io/repository/gkrumbach07/ttm-as-a-service:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local