name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  Worker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Worker.dockerfile
          push: true
          tags: quay.io/${{ secrets.QUAY_USERNAME }}/ttm-as-a-service-worker:latest,quay.io/${{ secrets.QUAY_USERNAME }}/ttm-as-a-service-worker:${{ env.RELEASE_VERSION }}

  Controller:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Controller.dockerfile
          push: true
          tags: quay.io/${{ secrets.QUAY_USERNAME }}/ttm-as-a-service-controller:latest,quay.io/${{ secrets.QUAY_USERNAME }}/ttm-as-a-service-controller:${{ env.RELEASE_VERSION }}